[colors.primary]
background = "#232538"
foreground = "#f2f2f2"

[colors.cursor]
text = "CellForeground"
cursor = "#d1d2e0"

[colors.selection]
text = "CellForeground"
background = "#3b3e5e"

[colors.normal]
black = "#5c608a"
red = "#ff8080"
green = "#80ff99"
yellow = "#ffdd80"
blue = "#809fff"
magenta = "#d580ff"
cyan = "#80eaff"
white = "#d1d2e0"

[colors.bright]
black = "#5c608a"
red = "#ff8080"
green = "#80ff99"
yellow = "#ffdd80"
blue = "#809fff"
magenta = "#d580ff"
cyan = "#80eaff"
white = "#d1d2e0"
