[colors.primary]
background = "#1f222e"
foreground = "#e0e0e0"

[colors.cursor]
text = "CellForeground"
cursor = "#a9b0c6"

[colors.selection]
text = "CellForeground"
background = "#243b6b"

[colors.normal]
black = "#757fa3"
red = "#de7c7c"
green = "#7cde7c"
yellow = "#dccb74"
blue = "#7094db"
magenta = "#be7cde"
cyan = "#64d8c5"
white = "#a9b0c6"

[colors.bright]
black = "#757fa3"
red = "#de7c7c"
green = "#7cde7c"
yellow = "#dccb74"
blue = "#7094db"
magenta = "#be7cde"
cyan = "#64d8c5"
white = "#a9b0c6"
