[colors.primary]
background = "#252537"
foreground = "#f2f2f2"

[colors.cursor]
text = "CellForeground"
cursor = "#d1d1e0"

[colors.selection]
text = "CellForeground"
background = "#3d3d5c"

[colors.normal]
black = "#5c5c8a"
red = "#ff8f8f"
green = "#8fffa5"
yellow = "#ffe18f"
blue = "#8fabff"
magenta = "#da8fff"
cyan = "#8fecff"
white = "#d1d1e0"

[colors.bright]
black = "#5c5c8a"
red = "#ff8f8f"
green = "#8fffa5"
yellow = "#ffe18f"
blue = "#8fabff"
magenta = "#da8fff"
cyan = "#8fecff"
white = "#d1d1e0"
